format_version = 1

[package]
name    = "S7"
since   = "0.2.2"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/S7"

[capabilities]
r_shims    = false
extern_raw = false
