format_version = 1

[package]
name    = "magrittr"
since   = "2.0.5"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/magrittr"

[capabilities]
r_shims    = false
extern_raw = false
