format_version = 1

[package]
name    = "fs"
since   = "2.1.0"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/fs"

[capabilities]
r_shims    = false
extern_raw = false
