format_version = 1

[package]
name    = "Rcpp"
since   = "1.1.1.1.1"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/Rcpp"

[capabilities]
r_shims    = false
extern_raw = false
