format_version = 1

[package]
name    = "processx"
since   = "3.9.0"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/processx"

[capabilities]
r_shims    = false
extern_raw = false
