format_version = 1

[package]
name    = "jsonlite"
since   = "2.0.0"

[definition]
version = "0.2.0"
tier    = "T3"

[provider]
type       = "community"
repository = "github:we-data-ch/registry/definitions/jsonlite"

[capabilities]
r_shims    = false
extern_raw = false
