format_version = 1

[package]
name    = "utf8"
since   = "1.2.6"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/utf8"

[capabilities]
r_shims    = false
extern_raw = false
