format_version = 1

[package]
name    = "curl"
since   = "7.1.0"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/curl"

[capabilities]
r_shims    = false
extern_raw = false
