format_version = 1

[package]
name    = "withr"
since   = "3.0.2"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/withr"

[capabilities]
r_shims    = false
extern_raw = false
