format_version = 1

[package]
name    = "generics"
since   = "0.1.4"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/generics"

[capabilities]
r_shims    = false
extern_raw = false
