format_version = 1

[package]
name    = "tibble"
since   = "3.3.1"

[definition]
version = "0.1.0"
tier    = "T3"

[provider]
type       = "generated"
repository = "github:we-data-ch/registry/definitions/tibble"

[capabilities]
r_shims    = false
extern_raw = false
